# Generated by Django 3.1.4 on 2020-12-19 18:59

from django.db import migrations, models
import django.db.models.deletion
import store.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='media')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=15, verbose_name='Country')),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='media')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('shortSpecifications', models.TextField(max_length=500, null=True, verbose_name='Short specifications')),
                ('specifications', models.TextField(max_length=3000, null=True, verbose_name='Specifications')),
                ('price', models.PositiveIntegerField(validators=[store.validations.validate_price], verbose_name='Price')),
                ('discount', models.PositiveSmallIntegerField(default=0, null=True, validators=[store.validations.validate_discount], verbose_name='Discount')),
                ('year', models.PositiveSmallIntegerField(default=2020, validators=[store.validations.validate_product_year], verbose_name='Year')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
