# Generated by Django 3.1.4 on 2020-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201221_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales'),
        ),
    ]
