# Generated by Django 3.1.4 on 2020-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_imageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='images'),
        ),
    ]
