# Generated by Django 3.1.4 on 2020-12-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201223_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
