# Generated by Django 3.1.4 on 2021-01-18 19:09

from django.db import migrations, models
import store.validations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201227_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, validators=[store.validations.validate_product_year], verbose_name='Year'),
        ),
    ]
