# Generated by Django 3.1.4 on 2021-02-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210212_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-updated',)},
        ),
    ]
