# Generated by Django 3.1.4 on 2021-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210212_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='disadvantages',
            field=models.CharField(max_length=200),
        ),
    ]
