# Generated by Django 4.1.7 on 2023-03-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(max_length=3000, null=True, verbose_name='Specifications'),
        ),
    ]
