# Generated by Django 3.1.4 on 2021-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210405_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
