# Generated by Django 3.1.4 on 2021-04-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210406_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer_phone',
            new_name='phone',
        ),
    ]
