# Generated by Django 4.1.7 on 2023-03-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210409_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profiles/placeholder.png', null=True, upload_to='images/profiles/'),
        ),
    ]
