# Generated by Django 3.1.4 on 2021-01-22 19:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='items',
            field=jsonfield.fields.JSONField(),
        ),
    ]
