# Generated by Django 3.1.4 on 2021-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210122_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='items',
            new_name='cart_items',
        ),
    ]
