# Generated by Django 3.1.4 on 2021-01-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210122_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='cart_items',
            new_name='items',
        ),
    ]
