# Generated by Django 3.1.4 on 2021-01-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210122_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
