# Generated by Django 3.1.4 on 2021-01-26 20:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210125_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='items_wishlist',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
