# Generated by Django 3.1.4 on 2021-03-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_usercart_items_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='coupon',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
