# Generated by Django 4.1.7 on 2023-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_usercart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='message_id',
            field=models.IntegerField(default=-1),
        ),
    ]
