# Generated by Django 3.1.4 on 2021-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
    ]
