# Generated by Django 3.1.4 on 2021-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210307_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=6886867454, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Post office', 'Post office')], default='Courier', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal'), ('PrivatPay', 'PrivatPay')], default='Cash', max_length=20),
        ),
    ]
