# Generated by Django 3.1.4 on 2021-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210523_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Post office', 'Post office')], default='Courier', max_length=15, null=True),
        ),
    ]
