# Generated by Django 3.1.4 on 2021-05-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Post office', 'Post office')], default='Courier', max_length=15, null=True),
        ),
    ]
