# Generated by Django 3.1.4 on 2021-05-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210524_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal')], default='Cash', max_length=20),
        ),
    ]
