# Generated by Django 4.1.7 on 2023-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
